baseURL = "https://jdonejdk.github.io"
title = "jdonejdk's blog"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "jdonejdk"
    badge = "orange"
    quote = "red"
    index_posts_num = 5
    google_search = true
    logo = "/self/img/avater.jpg"
    bio = """
    <p> 渡人亦是渡己 </p>
    <br />
    <p>哈哈哈哈，其实就是做着玩</p>
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "zone"
    name = "Zone"
    url = "/zone/"
    weight = 10

# [[menu.footer]]
#     identifier = "home"
#     name = "home"
#     url = "/"
#     weight = 1

# [[menu.footer]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "https://github.com/jdonejdk/"
    name = "github"
    weight = 1

